/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d3e4fe",
        "secondary-container": "#86f2e4",
        "on-secondary-fixed-variant": "#005049",
        "inverse-surface": "#213145",
        "outline-variant": "#c6c6cd",
        "on-background": "#0b1c30",
        "primary-fixed": "#dae2fd",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed": "#fcdeb5",
        "inverse-primary": "#bec6e0",
        "surface-container-high": "#dce9ff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45464d",
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-container": "#98805d",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "background": "#f8f9ff",
        "secondary": "#006a61",
        "on-primary-container": "#7c839b",
        "surface": "#f8f9ff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#006f66",
        "on-tertiary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#131b2e",
        "surface-tint": "#565e74",
        "surface-container": "#e5eeff",
        "primary-container": "#131b2e",
        "tertiary-container": "#271901",
        "primary": "#000000",
        "on-tertiary-fixed-variant": "#574425",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed-dim": "#dec29a",
        "secondary-fixed": "#89f5e7",
        "primary-fixed-dim": "#bec6e0",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "outline": "#76777d",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed": "#271901",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed": "#00201d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "1rem",
        "sidebar-width": "260px",
        "header-height": "64px",
        "gutter": "1.5rem",
        "stack-sm": "0.5rem",
        "container-padding": "2rem",
        "stack-lg": "1.5rem"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "data-mono": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
